version: '3.4'

services:
  webapi:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: posreversalnibbs-api
    ports:
      - "8085:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PosNibbsConnection=Server=10.100.0.120;Database=PosReversalNibbsDB;user id=posreversaluserms; password=Posreversaluserms1;Encrypt=True;TrustServerCertificate=True
     
     
